server:
  port: 8081
# 用户家目录下
#spring.datasource.url = jdbc:h2:file:~/.h2/testdb
spring:
  datasource:
    url: jdbc:h2:file:D:\\h2\\db\\testdb
    data-username: sa
    data-password: sa
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
 # activiti:
  #  check-process-definitions: true #自动检查、部署流程定义文件
   # database-schema-update: true #自动更新数据库结构
   # process-definition-location-prefix: classpath:/processes/ #流程定义文件存放目录
    #process-definition-location-suffixes: #流程文件格式
    #  - **.bpmn20.xml
    # - **.bpmn